# backend:
#   name: github
#   repo: booklice/booklice
#   branch: main
#   base_url: https://sveltia-auth.youngjo.workers.dev

backend:
  name: test-repo

logo:
  src: ../assets/logo.jpg
  show_in_header: true

app_title: Hwang Soo Hyun

media_folder: /static/assets
public_folder: /assets

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 80
          width: 1200
          height: 1200
        svg:
          optimize: true

collections:
  - name: biography
    label: Biography
    files:
      - name: biography
        label: Biography
        file: content/biography/biography.md
        fields:
          - name: experience
            label: 경력
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

          - name: awards
            label: 수상
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

          - name: residencies
            label: 레지던시
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

          - name: education_workshops
            label: 교육 및 워크숍
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

          - name: choreography
            label: 안무작
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

          - name: collaborations
            label: 협업 및 협력 프로젝트
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

          - name: performances
            label: 출연작
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: title, label: 내용, widget: string }

  - name: work
    label: Work
    folder: /content/work
    create: true
    media_folder: "{{media_folder}}/work/{{slug}}"
    public_folder: "{{public_folder}}/work/{{slug}}"
    fields:
      - name: title
        label: 제목
        widget: string
        required: true

      - name: workType
        label: 작업 유형
        widget: string
        required: true

      - name: startDate
        label: 시작 날짜
        widget: datetime
        type: date
        required: true

      - name: endDate
        label: 종료 날짜
        widget: datetime
        type: date
        required: true

      - name: venue
        label: 공연 장소
        widget: string
        required: true

      - name: credit
        label: 크레딧
        widget: textarea
        required: true

      - name: production
        label: 제작, 주최 및 후원
        widget: text

      - name: description
        label: 작품 내용
        widget: text
        required: true

      - name: articles
        label: 기사
        widget: list
        required: false
        fields:
          - name: title
            label: 제목
            widget: string

          - name: url
            label: 링크
            widget: string

      - name: critics
        label: 비평
        widget: list
        required: false
        fields:
          - name: title
            label: 제목
            widget: string

          - name: url
            label: 링크
            widget: string

      - name: images
        label: 이미지
        widget: file
        multiple: true
        required: false
